language: android
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sereiponna-github"
    token:
      secure: "cJvtMa04uDFCGU7A69Qh/054fvTACjVWJPsNekHI1kMXCHe4QlrPQHKoLoN8RKJtPt2/IAq13H57CdMOq6e/KMz35avsJCMH8EmKA9gWTYIn/XbW0fYI/aIoFQWh6/e0i9Oem8S7/ModJW6reDaT3el8uMG7/BF/8iHx1auov+MHDv9yuJY+EWe3Os8GhTUB/PvfF9rONLduoN2LEHiDuv2DMfP7b/N3DgYvywMSWJ7HKYVIHRVPrpy5FPC2Tx4gbig19Q7bnYEDPTkxmWgHn1QjT1lpxe8WSVeEahg5UJFj5g9RcKf00KidaSwSBstZODv9mTMWHjgNJwSrjoB4jxbd2qsO+fSkPQpiaiG0EoBwdKLbQd7Hd5w3M4n5kVWLV+Gy8i+cAb+lH3yFVDQOj4OiQ2gp1xzvCgSVsgcfX4UCCfANn0cnbuaQ/eHZd2C12s2vlQrsgkBCskym96fywbzqQSuoAhQadgU91OcTKjfK2+vIQg2U/rdwbyRnyqQyi0B3APHfMqaRNSp+1RN5n+F+QIYL941XQUavg9lpVh6QApfDiWC/7wkLCFZfPTnr174XPzzPQyoB44DboUs5Ivr+cQrThqO2wJELASrGkwxGTyyPJ14JJXg74ZsnG6kSRM4O6OujkE+aJKJ7Qm/GrckXlDF3N+CaTm4vapXq5e8="
      
#android:
#  components:
#    - tools
#    - platform-tools
#    - tools
#    - build-tools-25.0.3
#    - android-25
#  licenses:
#    - android-sdk-preview-license-.+
#    - android-sdk-license-.+
#    - google-gdk-license-.+
#    - '.+'

before_install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false