language: android
sudo: false
install: true

addons:
  sonarcloud:
    organization: "kitswdevteam-github"
    token:
      secure: "AIGp1XDkO9UsPBU9pfOg7ofgZ1e3M8y56MWY+0apAEvNnQlsuHMWlMOjd+QFcJehzVxSKGvHY1FyA7vxemDdnmeiU/iAs8AgqN1Um1hokxjVV2WTb67DMt7BNj83NuzVoKmYREL7NRerCL98Fpaurs8UUQU3wuH6/ddGAtKUiUMe0g4y23CfIx9U+upWbcspXZEoOjo1IJVFH+Kv15nMnV8Y4PoT5KV20WvGp5jgP33uMwt29Y3Oq62ztP847VAgrlMx1ikjMkWQirScSRLEQWIwiF3IYC9BYOfA7+Psj6bGEdakVriRujUi4sN5pzOyhVKo7YkfEplbm+nJtVspCqCIyPmUiGMhvg5J813Mcz4rLqmZzLMlTZNnkdF4NHIm6NlG0/+5DWUSB3Z00jp+WipNolyFhd9/c13/DfG3e+LDGLl8VviKaUIBE+Y9x+aanXdKM0d5qZ3Z2c5Q2++CWoD24eqJEwZCYgGIGC89/w4oLEgS1pG6EtQ4m069L1cPwWCchUYjpZt+Q74B55YmD9BkH2t2SQDRilr1/j0spMD4LZ34v8FSA/NIarBez4AjCe+cZf0LrGgDL7tbmySIIXntTZWYwQOXeX86nBYXNIlX8iNXtlWUbfWSrEAN3tRGF5oUCUriyXXtVcIJAZerP+10FUETcbAzr9sQqj5JaYM="

#android:
#  components:
#    - tools
#    - platform-tools
#    - tools
#    - build-tools-25.0.3
#    - android-25
#  licenses:
#    - android-sdk-preview-license-.+
#    - android-sdk-license-.+
#    - google-gdk-license-.+
#    - '.+'

before_install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false